$ANSIBLE_VAULT;1.1;AES256
63626365656161336434383334643964656265343137363135376265386539323634333761313631
3439653839356466356536373132313663353736346664330a633935636333396364636239396435
66303430316332616138383237333133623437326230396164623966316262653361376536383532
6136336161356566650a633639313663613531353231353531646539616536666262393139323735
39626233333935306563386233376666346531373732316661366335383331643930613266373939
3362383561396163633938313232643364323766353430396638
