---
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
  name: clickhouse

- src: git@github.com:artharthur/vector-role.git
  scm: git
  version: "1.0.1"
  name: vector

- src: git@github.com:artharthur/lighthouse-role.git
  scm: git
  version: "1.0.1"
  name: lighthouse
