---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 192.168.1.68
      ansible_user: root
      ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q root@192.168.1.83"'

vector:
  hosts:
    vector-01:
      ansible_host: 192.168.1.71
      ansible_user: root
      ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q root@192.168.1.83"'

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 192.168.1.51
      ansible_user: root
      ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q root@192.168.1.83"'
